services:
  pricestream:
    image: pricestream
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    networks:
      - app_network

  websocketclient:
    build:
        context: ./ExchangeWebSocketClient
        dockerfile: Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - app_network
    deploy:
        replicas: 2
    entrypoint: >
        sh -c "sleep 2 && dotnet ExchangeWebSocketClient.dll"

networks:
  app_network:
    driver: bridge